package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 10 11:53:13 EET 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DeptResponseImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DeptResponseImpl() {
    }
}

